# File name: test.py
#:kivy 1.8.0

#: import FadeTransition kivy.uix.screenmanager.FadeTransition

ScreenManagement:
    transition: FadeTransition()
    MainScreen:
    AnotherScreen:
    

<MainScreen>:
    name: 'main'
    Button:
        on_release: app.root.current = 'other'
        text: 'Next Screen'
        font_size: 50
        
<AnotherScreen>:
    name: 'other'
    Painter
    Button:
        color: 0,0,1,1
        size_hint: 0.3, 0.2
        pos_hint: {'right':1, 'top':1}
        text: 'returnerino'
        on_release: app.root.current = 'main'